import cv2
import numpy as np
import os
from sklearn.model_selection import train_test_split

# Function to load images and labels
def load_data(image_dir):
    images = []
    labels = []
    for label in os.listdir(image_dir):
        label_dir = os.path.join(image_dir, label)
        if os.path.isdir(label_dir):
            for img_file in os.listdir(label_dir):
                img_path = os.path.join(label_dir, img_file)
                img = cv2.imread(img_path)
                img = cv2.resize(img, (128, 128))  # Resize images
                images.append(img)
                labels.append(label)  # Assuming label is the folder name
    return np.array(images), np.array(labels)

# Load data
image_directory = 'path/to/your/image_dataset'  # Update this path
X, y = load_data(image_directory)

# Convert labels to integers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape: {X_train.shape}, Labels shape: {y_train.shape}")
print(f"Testing data shape: {X_test.shape}, Labels shape: {y_test.shape}")
